#!/usr/bin/env bash
# install load balancer
apt-get update -y && \
apt-get install -y software-properties-common && \
add-apt-repository -y ppa:vbernat/haproxy-1.7 && \
apt-get update -y && \
apt-get install -y haproxy && \
if [ -e '/etc/haproxy/haproxy.cfg.orig' ]
then
    cat /etc/haproxy/haproxy.cfg.orig > /etc/haproxy/haproxy.cfg
else
    cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
fi
echo -e \
"\nlisten load_balancer
\tbind :80
\tmode http
\tstats enable
\tstats uri /haproxy?stats
\tbalance roundrobin
\tserver 1591-web-01 34.74.130.170:80 check
\tserver 1591-web-02 34.235.167.111:80 check" \
    >> /etc/haproxy/haproxy.cfg
service haproxy restart
