#!/usr/bin/env bash
# A shell script to print each number of clock.
j=0
while [ $j -le 12 ]
do
    i=1
    echo "Hour: $j"
    while [ $i -le 59 ]
    do
        echo $i
        ((i++))
    done
    ((j++))
done
