#!/usr/bin/env bash
# Fix container to run nginx
sudo pkill apache2
sleep 2
sudo chmod ugo+rw /etc/nginx/nginx.conf
sed -i -E 's/(listen.*)80 /\18080 /g' /etc/nginx/sites-enabled/default
sudo -u nginx nginx
